### ISSUE TITLE
Development ToDo

### ISSUE THREAD

**Issue by tzuntar** [tzuntar/FiveM-WhitelistBot#3]
Short-term goals:

- [ ]  Create a possibly missing `whitelist` table in the target database instances
- [ ]  Store the credentials in the db_instances table more securely
    - make sure there's absolutely no way to access them directly
    - delete the database registration messages after a database is registered to make sure no other server members can see them
- [ ]  Write unit tests for most of the newly added methods

Mid-term goals:

- [x]  The bot runs on a PC which possibly has no other mysql instances running
- [ ]  It should be possible to load the data from multiple config files
- [ ]  The bot should be able to cache certain things to provide limited features when the game database is offline
- [ ]  Better error handling and resiliency
- [x]  Explore options for replacing the guild database IDs with snowflakes in the local datastore
- [x]  Help messages (use fields in the Command interface?)
- [x]  Use inline embed fields when listing the whitelisted users
